### PR TITLE
I made some of the code a bit smoother

### PR DESCRIPTION
**Pull request by KingDevCode**
- Added a Utilities class to get some handy functions to use in the code
- Changed the code of every command
- Edited the code of the listeners

### CODE REVIEW

**Comment by OmeWillem** [comment]
no bitches?

**Comment by Tiebienotjuh** [comment]
Why did you remove the hol blacklist system?

**Comment by KingDevCode** [comment]
Because it was bugging. The plugin was not starting up. It kept standing on enabling. Maybe but it in async runnable or something?

**Comment by TheBathDuck** [comment]
First of all, you removed the blacklist system. This system is made for servers that sell the collectibles for money on their store. This system is here to blacklist these servers. Also, some methods are static abuse and shouldn't be used. This isn't bugging if the server has a valid internet connection.

You also replaced the colorize method? I don't see why as the previous method works & is perfect. You replaced some chars with `§` instead of using the colorize method.

The `Utilities.java` class you have added is not really usefull as I make use of ItemBuilder so this class is not nessesary at all.

So what happend here?

**Comment by KingDevCode** [comment]
You see what you do...

**Pull request closed without merging**
